// File generated by hand on 2026-09-22 (Task-23) from
// android/app/google-services.json, because FlutterFire CLI 1.4.1 could not
// resolve the project through firebase-tools 15.30.2. Same shape as the file
// `flutterfire configure` writes. Android only (docs/TASKS_INDEX.md, Later).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJysXgGx_ZP-qDA5pPH4UiDoww3dpgeuM',
    appId: '1:125884332328:android:e6150153bf7a3e5ce7381d',
    messagingSenderId: '125884332328',
    projectId: 'terra-nt-cdu',
    storageBucket: 'terra-nt-cdu.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJG-Jz_tHbV5_WfAFWKbXyMEBel9A_yE',
    appId: '1:125884332328:ios:a32039f5a3fc95ffe7381d',
    messagingSenderId: '125884332328',
    projectId: 'terra-nt-cdu',
    storageBucket: 'terra-nt-cdu.firebasestorage.app',
    androidClientId: '125884332328-7htv8i16mq45hvekbfl42n18mv3e9deg.apps.googleusercontent.com',
    iosClientId: '125884332328-j4b8ii2peb01qu2fpp0l6qlrip2i0k54.apps.googleusercontent.com',
    iosBundleId: 'au.edu.cdu.terraNt',
  );
}
